language: node_js
sudo: false
node_js:
  - 11
install:
  - npm install
script:
  - npm run build
  after_success:
  - firebase deploy --project codeclubph --token $FIREBASE_TOKEN
  deploy:
    provider: firebase
    token:
      secure: ""
